mesa={}
mesa[1] = {"Livre","2", "NA"}
mesa[2] = {"Livre","2", "NA"}
mesa[3] = {"Livre","2", "NA"}
mesa[4] = {"Livre","4", "NA"}
mesa[5] = {"Livre","4", "NA"}
mesa[6] = {"Livre","4", "NA"}
mesa[7] = {"Livre","6", "NA"}
mesa[8] = {"Livre","6", "NA"}
mesa[9] = {"Livre","6", "NA"}
mesa[10] = {"Livre","8", "NA"}
mesa["Mesa"] = {"Estado","Lugares","Horario"}
